#%RAML 1.0 Trait
headers:
  x-vioc-msgId:
    description: This header contains transaction id which will be uniquely identify the transaction.
    required: true
    type: string
    minLength: 36
    maxLength: 36
    example: "090hdsfhjdh-jxbv859-sjdf7643-3746bbd"